spring:

  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://81.208.172.32:3306/bscard
    username: root
    password: ssafy




  jackson:
    time-zone: Asia/Seoul


  mail:
    default-encoding: UTF-8
    host: smtp.naver.com
    port: 587
    username: junwon1131@naver.com
    password: KNY95F5E68R5
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true



  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false  # SSE ??? ?? -> DB Connection ??? connection ?? ??
  data:
    redis:
      url: redis://81.208.172.32:6379


cloud:
  aws:
    credentials:
      access-key: AKIARI2J3RH43CRK24NB
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: ssafybizcard
      stack:
        auto: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: prometheus

logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG

server:
  port: 8080
  servlet:
    context-path: /

